apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-hvoo
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0063-tenant/tkrw-pr712-0075-0063-app/devfile-sample-hvoo@sha256:9a6c852e78ac597cdd10d8ce1f766a382812d23e615e3cb327f86c346dabeb52
        name: my-nodejs
        resources: {}
status: {}
